### ISSUE TITLE
Github actions test BMR

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/icon-bridge#126]
As follow up to #109, the next step is to add a command to test the relay. This should just be adding a `go test` command. It would be good to also look into whether we can plug in Codecov.io to this as well.

## Acceptance Criteria

- Add BMR testing in CI process to github action
- See if we can also add code coverage info via Codecov.io

**Comment by andrii-kl** [comment]
https://github.com/icon-project/icon-bridge/pull/365
