### ISSUE TITLE
Action to manually deploy contracts in Testnet

### ISSUE THREAD

**Issue by pragyanshrestha-ibriz** [icon-project/icon-bridge#236]
## Overview
Action to manually deploy contracts (and related BMR) in testnet by choosing release tag, followed by publishing the deployed contract addresses in a protected github branch.

## Acceptance Criteria
Manual actions that can be triggered from the Actions tab for deploying the contracts on Testnet

**Comment by dwdraju** [comment]
Duplicate issue of https://github.com/icon-project/icon-bridge/issues/217
