### ISSUE TITLE
One token transfer not showing on ICON

### ISSUE THREAD

**Issue by FezBox** [icon-project/icon-bridge#27]
I managed to move 1 One token from harmony to ICON

I had to speed up the transaction on metamask for it to work
https://explorer.harmony.one/tx/0x0ba57a3341a04cde0e6421d69224b57da7aa17137a15a450b4e1e6953ac55f44
![image](https://user-images.githubusercontent.com/107530591/177251413-0424c2d7-b6fe-4baf-947a-f332a73b99a1.png)

Nexus shows it's successful however I can't see it in my wallet. i can't find the token on the tracker to add the address
https://tracker.icon.foundation/address/hxa549560d0ca644c1a8f0f110f061ed9adef9b5a9#transactions

**Comment by CyrusVorwald-ICON** [comment]
Closed as not an issue with icon-bridge. @robcxyz please link the issue in the tracker here
