### ISSUE TITLE
Deployment Checklist Documentation

### ISSUE THREAD

**Issue by pragyanshrestha-ibriz** [icon-project/icon-bridge#329]
This is a draft checklist that will be converted to a markdown documentation after incorporating suggestions from different teams.

**Comment by bbist** [comment]
Pre-Deployment Checklist:
1. Make sure that receiver is able to work with mainnet at expected throughput.

Mainnet Initial Deployment Checklist:
1. Setup the system to be used for deployment, pre-install all the dependencies required by the deployment script.
    1. Generate keystores to be used as god wallet for deployment
    2. Fund generated god wallets to have some minimum balance required for full deployment
2. Use dedicated RPC endpoints for deployment. Also, try to make deployment script as stable as possible.
3. Always start with testnet deployment and verify methods are working.
4. After mainnet deployment, verify all readonly methods of each contract are showing expected values.
5. Remove deployer (god wallet) as owner.
6. Fund mainnet BMR wallets.
7. AWS secrets manager configuration on ICONLoop server. Send Ajaya's video.
8. Setup monitoring on BMR instance before running BMR.
9. Add slack webhook url on BMR config. Make sure that BMR configuration like sync concurrency and other parameters are appropriately set.
10. Investigate system resource utilization after BMR deployment, netstat (active connections to RPC endpoints, CPU, RAM utilization, Disk Usage, etc)
11. Git tagging/versioning of code after each deployment and upgrade.
12. Publish mainnet deployment details on github for Nexus/Marketing Team, contract addresses and network details.
13. Run full smoke and e2e tests on testnet, followed by smoke tests on mainnet.
14. Don't remove the deployment code after deployment, need it for later upgrade. 

Mainnet BMR Upgrade:
1. 


Mainnet Contract Upgrade:
1. 


Mainnet Code Review Session:
1.
