### ISSUE TITLE
Implement BSC block verification

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/icon-bridge#35]
## Overview
The relay should verify correctness of incoming messages the same way that the BMV does.

## Rationale
We want to mimic the functionality of BTP as closely as possible. This means moving the on-chain verification component to the off-chain relay. Additionally, if the RPC endpoint is hijacked, false messages can be supplied.

## Acceptance Criteria

- [ ]  Add a BSC verifier similar to https://github.com/icon-project/icon-bridge/blob/f5d98e56b71a3ba24cfee176bf640406323e2aa3/cmd/btpsimple/chain/hmny/verifier.go and connected functionality in the client and receiver.

**Comment by pragyanshrestha-ibriz** [comment]
pending review from @bbist

**Comment by pragyanshrestha-ibriz** [comment]
review completed. Merge pending

**Comment by manishbista28** [comment]
Implemented with
https://github.com/icon-project/icon-bridge/issues/377
