### ISSUE TITLE
Add CodeQL static analysis workflow

### ISSUE THREAD

**Issue by CyrusVorwald-ICON** [icon-project/icon-bridge#355]
## Overview
Now that the repo is open sourced, we can add CodeQL to scan the Java and Go code bases for vulnerabilities

## Rationale
CodeQL automates security checks for open source repositories

## Acceptance Criteria

- CodeQL workflow runs and passes

**Comment by CyrusVorwald-ICON** [comment]
The golang analyzer runs into a reported error https://github.com/github/codeql-action/issues/430

@dwdraju can you look into how to fix this?

**Comment by dwdraju** [comment]
@CyrusVorwald-ICON, we have stopped the e2e test also for hmny as it's no longer maintained afaik. The chain/hmny needs to be removed from package import. Updated [PR](https://github.com/icon-project/icon-bridge/pull/358)
