### ISSUE TITLE
Coin/Token Registration failing if decimal is above 21

### ISSUE THREAD

**Issue by MuhammedIrfan** [icon-project/icon-bridge#376]
## Steps to Reproduce
1. Register Coin with Decimals more than 21 Places
2. See errors
`FRAME[6] INVOKE done status=Reverted(0) msg=E0032:decimals needs to be equal or lower than 21 steps=33174`
3. Failed Transaction https://tracker.lisbon.icon.community/transaction/0xbfa0b9854b647d8a4db8f79130b4db81bbd4f676e518d7ff390bf7d8a72e262a

## Expected Behavior
Shouldn't limit the decimal

## Code
https://github.com/icon-project/icon-bridge/blob/main/javascore/irc2Tradeable/src/main/java/foundation/icon/btp/irc2Tradeable/IRC2Basic.java#L45

**Comment by izyak** [comment]
Similarly, the decimals of ERC20Tradable on the solidity contract is hardcoded to 18 because if it being hardcoded to 18 in the ERC20 library. A method that overrides decimals of ERC20 needs to be added to ERC20 Tradable contract.
