### ISSUE TITLE
Unified Icon-Bridge End-to-End Testing + Stress Testing

### ISSUE THREAD

**Issue by bbist** [icon-project/icon-bridge#4]
## Description
The tests used by each chain specific bridge differ significantly even though the core tests should remain the same for the BTP protocol. This introduces discrepancies across branches that are hard to track. Therefore, there is a need for a unified testing framework, specifically an end-to-end testing framework with the core set of tests shared across each individual BTP integration. This epic groups all issues (bug/feature) related to the implementation of such a framework.

## Initiative / goal
The end goal for this epic is to have a unified framework, a set of commands that can be used to handle build and deployment of individual blockchains, automated deployment of necessary smart contracts and their configuration, and build and deployment of end-to-end testing application.

### Milestones
1. Implement end-to-end test cases for each BSH (nativecoin, tokenbsh) between ICON and Harmony. Should have stress testing components built in.
2. Implement configurable core to take input parameters and dependencies for each supported chain using a JSON/YAML file.
3. Add support for BSC.
4. Add support for NEXT.

**Comment by CyrusVorwald-ICON** [comment]
Closing because all sub issues are closed.
