### ISSUE TITLE
Implement Service type for TokenLimit Request

### ISSUE THREAD

**Issue by shreyasbhat0** [icon-project/icon-bridge#433]
## Overview

Implement a new service type TokenLimit to handle token limit messages

## Story

As a bts, I want to set the token limit for the tokens registered so that token transfer should happen within that limit.

## Acceptance Criteria

List of requirements to be considered complete.

**Comment by CyrusVorwald-ICON** [comment]
Please add the associated sprints, estimate, epics, and releases.
