### ISSUE TITLE
Refactor RPC API to reuse method between E2E Test framework

### ISSUE THREAD

**Issue by MuhammedIrfan** [icon-project/icon-bridge#441]
## Overview
Refactor RPC API to reuse method between E2E Test framework, At present https://github.com/icon-project/icon-bridge/blob/hugobyte/development/cmd/iconbridge/chain/near/api.go does not effectively enable code to be reused and code is duplicated. This story targets on exposing method based on RPC methods which will effectively enable to compose the e2e test client to reuse the methods

## Acceptance Criteria
- [x] Expose methods reflecting RPC methods of the chain

**Comment by CyrusVorwald-ICON** [comment]
Please add the associated sprints, estimate, epics, and releases.

**Comment by MuhammedIrfan** [comment]
Using `https://github.com/MuhammedIrfan/testify-mock` package for mock until the PR https://github.com/stretchr/testify/pull/1266 gets merged
