### ISSUE TITLE
Script to configure and register token for BSC & Icon

### ISSUE THREAD

**Issue by dwdraju** [icon-project/icon-bridge#442]
## Overview
Implementation of following steps for generating BMR config:
For BSC
a. configure_solidity_add_bmc_owner
b. configure_solidity_add_bts_service
c. configure_solidity_set_fee_ratio
d. configure_solidity_add_bts_owner
e. Register BSC Tokens

Similar steps for ICON
a. configure_javascore_add_bmc_owner
b. configure_javascore_bmc_setFeeAggregator
c. configure_javascore_add_bts
d. configure_javascore_add_bts_owner
e. configure_javascore_bts_setICXFee
f. Register ICON Tokens

## Rationale
This feature is necessary for generating BMR config at deployment time

## Acceptance Criteria
Separate github actions for ICON and BSC to operate above steps and user should be able trigger the actions manually.

**Comment by CyrusVorwald-ICON** [comment]
Please add the associated sprints, estimate, and releases.
