### ISSUE TITLE
story(build): write utility scripts for transfer demo

### ISSUE THREAD

**Issue by manishbista28** [icon-project/icon-bridge#496]
## Overview
A set of scripts should be written that does transfer operation. This can be used to do the actual transfer or demo the operation of iconbridge.

## Story

It should be possible to use scripts to do the transfer operation.

## Acceptance Criteria
- Should be usable for any environment (testnet /local)

**Comment by CyrusVorwald-ICON** [comment]
does e2e already cover this?

**Comment by manishbista28** [comment]
Yes, e2e already includes a set of functions and scripts that perform transfer call.
What e2e does not expose is a way for a user to do a single transfer operation alone.

**Comment by CyrusVorwald-ICON** [comment]
Understood. I am against doing this for a couple reasons

1. all items that would go into this script should be part of the publicly documented API
2. users would use the publicly exposed api, not the bash script
3. a demo can be written by content writers after the documentation for the API is complete

**Comment by manishbista28** [comment]
Got it. I'll close the ticket for now.
