### ISSUE TITLE
feat(e2e): Update NEAR API to improve execution with config and proper logging

### ISSUE THREAD

**Issue by hemz10** [icon-project/icon-bridge#538]
## Overview

Update NEAR API to improve logging and config 

## Story

As a tester when i run e2e test I want

- config file to be specifiable from cmd line.
- Proper logging should be dropped on CLI and verbose logging should be stored on a log file
 so that it should be easy to run e2e after deploying contracts.

**Comment by MuhammedIrfan** [comment]
Kindly add the type
