### ISSUE TITLE
feat(bmc): Add setter getter tests for javascore BMC

### ISSUE THREAD

**Issue by izyak** [icon-project/icon-bridge#542]
## Feature
Add unit test for all setter and getter methods in javascore BMC

## Scenario
The case being tested

  * Given
    *  BMC Javascore is deployed.
  * When
    * Setter getter methods and all exceptions in setter method
        * add/remove Service
        * add/remove Link
        * add/remove Routes
        * add/remove serviceCandidates
        * relayer details
        * fee gathering details
  * Then
    * Required data should be set to variables while getting them

**Comment by CyrusVorwald-ICON** [comment]
Please add the given/when/then test scenario(s) to the description

  * Given
    *  The pre-conditions to the test.
  * When
    * The behavior to be tested.
  * Then
    * The expected outcome of the specified behavior.
