### ISSUE TITLE
Investigate the incompatibility issue between ICE and BSC (btp)

### ISSUE THREAD

**Issue by andrii-kl** [icon-project/icon-bridge#556]
### What needs to be done

Investigate if it's possible to reuse the **bmr** implementation of the BSM chain for ICE chain.

### Why it needs to be done

In the process of ICE integration (https://github.com/icon-project/icon-bridge/issues/501) I ran into several issues which cast doubt on the feasibility of trying to reuse the BMR BSC implementation.

### Additional Information

1) Block hash calculation algorithm is different for Eth and Substrate Eth chains.
**Go-ethereum** library what we use to communicate with BSM and ICE, doesn't store a block hash , it calculate it in runtime. So block hashes will be different with hashes that in the substrate Eth chains. (The Moonbeam chain has the same problem)

2)  BSC verification process will fail, because block parent hash won't match previous block hash.

**Comment by manishbista28** [comment]
BSC Verifier will not work with ICE. 
To disable verification, you can omit "verifier" key-value pair in relay config.
For example, the following config should be changed from
```
{
  "relays": [
    {
      "name": "b2i",
      "src": {
        "options": {
          "verifier": {
            "blockHeight": 23021962,
            "parentHash": "0x8e7ee3aaa23743ab9c3f77b7ca2d7765cf1b5698d2c46dbbf2a24880c8194df9",
            "validatorData": "0x.."
          },
          "syncConcurrency": 100
        },
        "offset": 23021962
      },
}
```

to
```
{
  "relays": [
    {
      "name": "b2i",
      "src": {
        "options": {
          "syncConcurrency": 100
        },
        "offset": 23021962
      },
}
```

**Comment by andrii-kl** [comment]
Thank you, I just removed verification to test the ICE. 
Right now I have a problem to test my implementation, e2e tests seem not works properly.

**Comment by andrii-kl** [comment]
I have created a simple app to reproduce and isolate current issue of getting block hash from substrate eth chains.  
This app compare behavior two clients go-substrate-rpc-client and go-ethereum and show differences.

[https://app.zenhub.com/files/471088677/c6e2437c-2d6d-4311-bbdb-eed1b766789c/download](https://app.zenhub.com/files/471088677/c6e2437c-2d6d-4311-bbdb-eed1b766789c/download)

**Comment by andrii-kl** [comment]
**Summary:**
BSC implementation is not usable for ICE/SNOW integration with any configuration changes or minor code changes.

Any functions that use Block.Hash() or Header.Hash() functions receive not right hash value. It means that all functionality should be reimplemented.

https://github.com/ethereum/go-ethereum/blob/c776a98c83ee0a8ab8d5eeb256884b14693f903d/core/types/block.go#L111

The right way to do ICE/SNOW integration it's to create a relay implementation for substrate-eth chains separately the bsc. But move common code in the general module.

**Comment by andrii-kl** [comment]
https://github.com/icon-project/icon-bridge/issues/601

**Comment by andrii-kl** [comment]
Integration plan discussion
https://github.com/icon-project/icon-bridge/discussions/603
