### ISSUE TITLE
chore: update workspaces sdk for functional testing

### ISSUE THREAD

**Issue by shreyasbhat0** [icon-project/icon-bridge#566]
## Overview

Add and Update new test cases for near bmc contract module

## Story

As a developer, I want near bmc contract modules to have maximum test cases which cover all the functionality  so that increases the code coverage 

## Acceptance Criteria

- Functional acceptance criteria to be met
- Non-functional acceptance criteria to be met

**Comment by MuhammedIrfan** [comment]
@shreyasbhat0 please add more details
