### ISSUE TITLE
Run e2e tests for the final SNOW version on the testnet 

### ISSUE THREAD

**Issue by andrii-kl** [icon-project/icon-bridge#621]
### What needs to be done

Run the e2e tests to check that all tests passed successfully, when SNOW integration be ready for deployment in the mainnet. 

Waiting fee calculation fix https://github.com/icon-project/icon-bridge/pull/610

**Comment by andrii-kl** [comment]
{
    "javascore": {
         "sICX" : "cx24358536f8d86339f2eec3e445504d856ed88dde",
         "bnUSD" : "cx4bec9eaf6b5f3cae128b785c1a1e749d2deb147d",
         "ICZ" : "cx9755006800249f4fe897fd52788e7c01fc3b4fd4",
         "bmc": "cx33cd64f1d667f56762ef304bdb42c1311430ff4f",
         "bts": "cx51ef0b67124015e499bf8c6b157c349b1393461d"
    },
    "solidity": {
         "ICX" : "0x02c2ee49dDaDE8C405df61A602C13871d8025Adc",
         "sICX" : "0xFa6b50A31cf3A59E680acf0cFE10522E11e65C13",
         "bnUSD" : "0x386822796024A069903f5c53e0d102df63A6805D",
         "BMCManagement": "0x63B4f88Fe27AB18928Cb91A3dAcD5aE882eed1D7",
         "BMCPeriphery": "0x28B6132FE02F5bFAb3fc5577209449D2b14122E6",
         "BTSCore": "0x2Dddc3c0D93F58BB12c421ceC75369849f08961d",
         "BTSPeriphery": "0xf6770999143225E1dA9e32F443dcAd7a1F4a56a8"
    }
}



https://github.com/icon-project/icon-bridge/issues/624#issuecomment-1282152738

**Comment by FezBox** [comment]
Andrii this says its deployed to Berlin, I believe it should be deployed to Lisbon

**Comment by andrii-kl** [comment]
The latest deployed contracts:

https://github.com/icon-project/icon-bridge/issues/689#issue-1417837499

https://github.com/icon-project/icon-bridge/issues/689
