### ISSUE TITLE
bridge icx - icx evm not working

### ISSUE THREAD

**Issue by chiavenna** [icon-project/icon-bridge#790]
Hello! i bridged 20 minutes ago, 119 ICX from ICON to SNOW EVM.....but i have not yet recived ICX EVM....this is the HASH
0xce88cb73e0be0e00d130b79bdbff91f626f008ace56282a415a1ccceeac73b64
and this is my destination address on ICX EVM..
0xaE3f0BFC11f820fa8d34C2E6614a39133CDA98d9

**Comment by CyrusVorwald-ICON** [comment]
Hello, this is an issue with the SNOW public RPC. It should go through once SNOW's archival node is back up. I am closing this issue for now and will check in once their RPC is back up to see if it persists.
